### ISSUE TITLE
Adding style tags into CKEDITOR html content

### ISSUE THREAD

**Issue by pionl** [uBlock-LLC/uBlock#1670]
Hi,

the uBlock adds a style tags into our CKEDITOR. Is there any solution to prevent this happening?

One time solution: We've added our website to whitelist.

```css
<style type="text/css">[href^="https://www.firstload.com/affiliate/"],
[href^="http://www.firstload.de/affiliate/"],
[href^="http://www.firstload.com/affiliate/"],
[href^="http://www.firstclass-download.com/"]
{display:none !important;}
</style>
<style type="text/css">[href^="https://www.firstload.com/affiliate/"],
[href^="http://www.firstload.de/affiliate/"],
[href^="http://www.firstload.com/affiliate/"],
[href^="http://www.firstclass-download.com/"]
{display:none !important;}
</style>
```
