### ISSUE TITLE
The "network request log" panel opens automatically at installation.

### ISSUE THREAD

**Issue by Percherie** [uBlock-LLC/uBlock#1764]
Good morning,

Within the framework of a deployment in a school, user profiles are fixed and lightened to the maximum. There is therefore no local profile for Firefox and it is automatically generated if the user uses the browser.

The uBlock extension is therefore placed in the Firefox installation folder"<firefox>/distribution/extension".

Problem, with each installation, uBlock opens the "network request log" side panel. How can we prevent it from opening?

By the way, why did you post it by default? This profoundly changes the user interface and only experienced users can use this console.

Translated with www.DeepL.com/Translator

**Comment by krystian3w** [comment]
You added question in wrong place... https://www.reddit.com/r/uBlockOrigin/ this is should better if have reddit account.

### Workaround

Hide with userChrome.css?

```css
vbox#sidebar-box[sidebarcommand="_UUID~ADDON_-sidebar-action"] {
   display: none !important;
}

vbox#sidebar-box[sidebarcommand="ublock0_raymondhill_net-sidebar-action"] {
   display: none !important;
}
```

`UUID~ADDON` version use when `ublock0_raymondhill_net` does not work
or using old µBlock 0.9.5.x (µBlock - have side panel...:question:).
