### ISSUE TITLE
[Firefox] Incompatibility between uBlock and Pentadactyl

### ISSUE THREAD

**Issue by mrz** [uBlock-LLC/uBlock#549]
Hello all.
Using uBlock in conjunction with Pentadactyl (http://5digits.org/pentadactyl/) breaks uBlock's icon. It would seem to be related to uBlock requiring the toolbar to work: executing the command "set go+=T" in pentadactyl fixes the issue and uBlock's badge starts working fine.

**Comment by Deathamns** [comment]
What is the conflict here? Obviously if you have the toolbar hidden, then you won't see the icon.
I installed the mentioned extension, opened a few pages, and µBlock still worked.

**Comment by mrz** [comment]
Mmh by default pentadactyl adds a new toolbar (the black one on bottom which you can see in this screenshot http://5digits.org/img/screenshots/dactyl-hints-all.png ) while hiding the standard navigation bar (the one with the URL bar and the search bar). From about:customizing you can drag extension icons to this "new" pentadactyl bar (notice how, in the screenshot, you can see NoScript icon in the far right corner of the bar - that's been dragged there by the user, since by default the bar has no icons). In my experience, uBlock's icon doesn't work when dragged to this bar, while other icons do. If you re-enable the standard navigation bar (using the command mentioned in the previous comment), it starts working again.

**Comment by Deathamns** [comment]
The icon does work, it even shows the number of the blocked elements.
However, the popup window won't be shown when the button is clicked (if that is what you mean).

**Comment by mrz** [comment]
Yes, that is what I'm seeing here. I realize the report wasn't precise enough now that you specified the difference between "number of blocked elements showing correctly" and "popup window not showing", sorry about that.

**Comment by behrmann** [comment]
Good someone already brought this issue up. Everything works, except for the popup window when moving the uBlock icon into pentadactyls bar. Since the popup seems to be the only way to access the dyanimc filtering, it would be nice if this issue could be resolved without having to add the toolbar to my FF (every time I want to change a setting).

**Comment by BryanJacobs** [comment]
This issue makes it very hard to use uBlock in any substantial way without giving up screen real estate for the address bar.

**Comment by behrmann** [comment]
A solution might be to look at the EFF's project privacybadger, since it has a popup with settings in clicking in the icon in the statusbar, which works with pentadactyl.

**Comment by Stebalien** [comment]
The popup works if the navigation bar is shown regardless of where the button is placed. You can hide the navigation bar without breaking the popup with the following css (using something like stylish):

``` css
#nav-bar {
    height: 0;
    overflow: hidden;
    visibility: hidden;
}
#nav-bar * {
    visibility: visible;
}
/* Blacklist the known nav-bar children */
#nav-bar-customization-target, #PanelUI-button, #window-controls, #nav-bar-overflow-buton {
    display: none;
}
```

It should be possible to whitelist only the popup and keep everything else hidden but I couldn't figure out what element I needed to whitelist:

``` css
#nav-bar {
    height: 0;
    overflow: hidden;
    visibility: hidden;
}
/* whitelist uBlock */
#nav-bar > #SomeElementId {
    visibility: visible;
}
```

Note: this _will_ break about:customizing.
